# Generated by Django 3.1.8 on 2023-12-02 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.TextField(verbose_name='Reaction')),
                ('time', models.TimeField(verbose_name='Time')),
                ('date', models.DateField(verbose_name='Date')),
                ('effect', models.FloatField(verbose_name='Effectiveness of Reaction')),
                ('responsible', models.CharField(max_length=120, verbose_name='Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Sel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=120, verbose_name='Disaster Name')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('crtDate', models.DateTimeField(auto_now_add=True, verbose_name='Creating Date')),
                ('MaximumPrecipitationIntensity', models.FloatField(verbose_name='Maximum Precipitation Intensity (mm/hour)')),
                ('SinglePrecipitationPeriod', models.FloatField(verbose_name='Single Precipitation Period (hour)')),
                ('AveragePrecipitation', models.FloatField(verbose_name='Average Precipitation (mm)')),
                ('MaximumWaterDepth', models.FloatField(verbose_name='Maximum Water Depth (cm)')),
                ('ConditionRoadTransportation', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Road Transportation Lines')),
                ('DamageArea', models.FloatField(verbose_name='Damage Area (km2)')),
                ('RescueWorker', models.FloatField(verbose_name='Rescue Worker (person)')),
                ('EmergencyResourceDuration', models.FloatField(verbose_name='Emergency Resource Arrival Duration (min)')),
                ('EmergencyResourceCompletenessReadiness', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Emergency Resource Completeness and Readiness Level')),
                ('AltitudeRegion', models.FloatField(verbose_name='Altitude of the Region (m)')),
                ('SlopeRegion', models.FloatField(verbose_name='Slope of the Region (1/m)')),
                ('BuildingDensityAccessibility', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Building Density and Accessibility of the Disaster Area')),
                ('terminate', models.BooleanField(default=False, verbose_name='terminate')),
                ('responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.responseplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCat',
            fields=[
                ('catId', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Catalogue  Id')),
                ('response', models.ManyToManyField(to='projects.ResponsePlan')),
            ],
        ),
        migrations.CreateModel(
            name='Deprem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=120, verbose_name='Disaster Name')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('crtDate', models.DateTimeField(auto_now_add=True, verbose_name='Creating Date')),
                ('MagnitudeEarthquake', models.FloatField(verbose_name='Magnitude of The Earthquake')),
                ('EmergencyTime', models.CharField(choices=[('1', 'Day'), ('2', 'Evening'), ('3', 'Night')], default=None, max_length=20, verbose_name='Emergency Time')),
                ('FocalDepth', models.FloatField(verbose_name='Focal Depth (km)')),
                ('EmergencyLocation', models.CharField(max_length=120, verbose_name='Emergency Location')),
                ('WeatherCondition', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Weather Condition')),
                ('BuildingCollapseRate', models.FloatField(verbose_name='Building Collapse Rate (%)')),
                ('PotentialSecondaryDisasters', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=None, max_length=20, verbose_name='Potential of Secondary Disasters')),
                ('PopulationDensity', models.FloatField(verbose_name='Population Density (n/km2)')),
                ('BuildingDensityAccessibilityDisasterArea', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Building Density and Accessibility of the Disaster Area')),
                ('PotentialHazardousMaterial', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Potential of Hazardous Material Arising from Debris')),
                ('EmergencyResourceCompleteness', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Emergency Resource Completeness and Readiness Level')),
                ('EmergencyResourceDuration', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Emergency Resource Arrival Duration')),
                ('InitialResponseLevel', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Initial Response Level of Local Units')),
                ('ConditionRoadTransportation', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Road Transportation Lines')),
                ('ConditionAirTransportation', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Air Transportation Lines')),
                ('ConditionRailwayTransportation', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Railway Transportation Lines')),
                ('ConditionMaritimeTransportation', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Maritime Transportation Lines')),
                ('ConditionHealthInfrastructure', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Health Infrastructure ')),
                ('ConditionWaterSupplySewage', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Water Supply and Sewage Systems')),
                ('ConditionCommunicationInfrastructure', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of Communication Infrastructure')),
                ('ConditionNaturalgas', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of the Natural Gas')),
                ('ConditionPowergrid', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Condition of the Power Grid')),
                ('SufficiencyTemporaryResidential', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Sufficiency of Temporary Residential Area')),
                ('CapacityWasteLandfills', models.CharField(choices=[('1', 'Definitely Low'), ('2', 'Very Low'), ('3', 'Low'), ('4', 'Medium'), ('5', 'High'), ('6', 'Very High'), ('7', 'Definitely High')], default=None, max_length=20, verbose_name='Capacity and Distance of Waste Landfills')),
                ('terminate', models.BooleanField(default=False, verbose_name='terminate')),
                ('responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.responsecat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
