# Generated by Django 3.1.8 on 2023-12-05 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deprems', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='sel',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.responsecat'),
        ),
        migrations.AlterField(
            model_name='sel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sels', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
