# Generated by Django 3.1.8 on 2023-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20231205_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprem',
            name='EmergencyLocation',
            field=models.CharField(choices=[('1', 'Marmara'), ('2', 'Ege'), ('3', 'Karadeniz'), ('4', 'Akdeniz'), ('5', 'Ic'), ('6', 'Dogu'), ('7', 'Guneydogu')], max_length=20, verbose_name='Emergency Location'),
        ),
    ]
