# Generated by Django 3.1.8 on 2023-12-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20231214_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprem',
            name='EmergencyLocation',
            field=models.CharField(choices=[('1', 'Marmara Bölgesi'), ('2', 'Ege Bölgesi'), ('3', 'Karadeniz Bölgesi'), ('4', 'Akdeniz Bölgesi'), ('5', 'İç Anadolu Bölgesi'), ('6', 'Doğu Anadolu Bölgesi'), ('7', 'Güneydoğu Anadolu Bölgesi')], max_length=20, verbose_name='Emergency Location'),
        ),
    ]
